#!/bin/bash

function init {
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
	curl https://get.volta.sh | bash
	~/.volta/bin/volta install node
echo "
export INITIALIZED=TRUE

eval \`ssh-agent\` 1>/dev/null
if [ \"\$?\" -eq 0 ]
then
	for i in \$(ls ~/.ssh/*.pub)
	do
		ssh-add "\$\(echo \$i \| sed 's/.pub//g'\)"
	done
fi" >> ~/.zshrc
}

if [ "$INITIALIZED" != "TRUE" ]
then
	init
fi